spring:
  application:
    name: pollpoll-api
  profiles:
    active: local
  config:
    import:
      - logging.yml

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
